# BUILD
# docker build -t frontend:0.1.0 -f DockerFile .
# RUN
# docker run -p 80:80 -d frontend:0.1.0

FROM node:14.18.1 as compilacion

COPY . /opt/app

WORKDIR /opt/app

RUN npm install

RUN npm run build

FROM nginx:1.21.3

COPY --from=compilacion /opt/app/build /usr/share/nginx/html
