# BUILD
# docker build -t backend:0.1.0 -f DockerFile .
# RUN
# docker run -p 8000:3800 -e POSTGRE_PASS=mysecretpassword -e POSTGRE_HOST=172.31.105.250 -d backend:0.1.0

FROM node:14.18.1

ENV POSTGRE_USER=postgres \
    POSTGRE_PASS=admin \
    POSTGRE_HOST=localhost \
    POSTGRE_DATABASE=postgres \
    POSTGRE_PORT=5432

COPY . /opt/app

WORKDIR /opt/app

RUN npm install

EXPOSE 3800

CMD ["npm", "start"]
